name: 🧪 checks

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - __tests__/fixtures/checks/**
      - .github/workflows/checks.yaml
      - .github/workflows/_test:checks.yaml

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
    with:
      package-path: __tests__/fixtures/checks

  checks-with-additional:
    uses: ./.github/workflows/checks.yaml
    with:
      package-path: __tests__/fixtures/checks
      additional-checks: |
        echo "all good!"
        dart format
