name: 🧪 test-unit

on:
  workflow_call:

jobs:
  test-unit:
    name: ${{ matrix.fixture }}
    strategy:
      matrix:
        fixture: [with-chrome, without-chrome, dart-basic, dart-dev, build-runner]

    uses: ./.github/workflows/test-unit.yaml
    with:
      package-path: __tests__/fixtures/test-unit/${{ matrix.fixture }}