name: 🧪 checks

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - __tests__/fixtures/checks/**
      - .github/workflows/checks.yaml
      - .github/workflows/_test:checks.yaml

jobs:
  checks:
    name: ${{ matrix.fixture }}
    strategy:
      matrix:
        fixture: [dart-dev, dart-basic]
    uses: ./.github/workflows/checks.yaml
    with:
      package-path: __tests__/fixtures/checks/${{ matrix.fixture }}


  checks-with-additional:
    uses: ./.github/workflows/checks.yaml
    with:
      package-path: __tests__/fixtures/checks/dart-dev
      additional-checks: |
        echo "all good!"
        dart format
