name: 🧪 test-unit

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - __tests__/fixtures/test-unit/**
      - .github/workflows/test-unit.yaml
      - .github/workflows/_test:test-unit.yaml

jobs:
  test-unit:
    name: ${{ matrix.fixture }}
    strategy:
      matrix:
        fixture: [with-chrome, without-chrome, dart-basic, dart-dev, build-runner]
    uses: ./.github/workflows/test-unit.yaml
    with:
      package-path: __tests__/fixtures/test-unit/${{ matrix.fixture }}